# Generated by Django 3.2.9 on 2021-11-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiChain', '0002_auto_20211109_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
